version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Ce435D3ea2CCf*2d2-DE-2G13b5Bf53*"
    volumes:
      - ./data:/var/lib/postgresql/data